import { useState } from 'react';
import { LockKeyhole, UserRound, ShieldCheck } from 'lucide-react';

const USERS_KEY='recon_control_users';
export const getUsers=()=>{ try { const x=JSON.parse(localStorage.getItem(USERS_KEY)||'[]'); return Array.isArray(x)?x:[]; } catch { return []; } };
export const seedAdmin=()=>{ const users=getUsers(); if(!users.length){ localStorage.setItem(USERS_KEY, JSON.stringify([{username:'admin',password:'admin123',name:'Administrator',role:'Admin'}])); } };
export default function Login({ onLogin }) {
  const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState('');
  const submit=e=>{e.preventDefault(); const user=getUsers().find(u=>u.username===username.trim()&&u.password===password); if(!user){setError('Username atau password salah.');return;} localStorage.setItem('recon_session',JSON.stringify({username:user.username,name:user.name,role:user.role})); onLogin(user);};
  return <div className="min-h-screen bg-[#f4f7fb] dark:bg-[#181C3B] flex items-center justify-center p-5"><div className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-8 shadow-xl dark:border-white/10 dark:bg-[#212743]"><div className="mx-auto mb-5 flex h-14 w-14 items-center justify-center rounded-2xl bg-[#181C3B] text-white"><ShieldCheck size={28}/></div><div className="text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-[#7088A9]">Secure Access</p><h1 className="mt-2 text-2xl font-black dark:text-white">Reconciliation Control Center</h1><p className="mt-2 text-sm text-slate-500">Silakan login untuk membuka dashboard.</p></div><form onSubmit={submit} className="mt-7 space-y-4"><label className="block"><span className="mb-1 block text-xs font-bold text-slate-500">Username</span><div className="flex items-center gap-2"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border border-slate-200 bg-slate-50 text-slate-400 dark:border-white/10 dark:bg-white/5"><UserRound size={18}/></span><input value={username} onChange={e=>setUsername(e.target.value)} className="field w-full" autoComplete="username"/></div></label><label className="block"><span className="mb-1 block text-xs font-bold text-slate-500">Password</span><div className="flex items-center gap-2"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border border-slate-200 bg-slate-50 text-slate-400 dark:border-white/10 dark:bg-white/5"><LockKeyhole size={18}/></span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} className="field w-full" autoComplete="current-password"/></div></label>{error&&<p className="rounded-xl bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</p>}<button className="w-full rounded-xl bg-[#181C3B] py-3 text-sm font-black text-white hover:opacity-90 dark:bg-white dark:text-[#181C3B]">Login</button></form><p className="mt-5 text-center text-[11px] text-slate-400">Akun awal: admin / admin123. Ganti melalui Pengaturan setelah login.</p></div></div>;
}
